version '3.7'

volumes:
  database_data:
    driver: local

services:
  db:
    image: 'postgres:13.2-alpine'
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - '8000:8000'
    links:
      - db